# Generated by Django 4.0.1 on 2022-06-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='clean',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='room',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=60, null=True),
        ),
    ]
