# Generated by Django 4.0.1 on 2022-05-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('id_proof', models.ImageField(upload_to='document')),
                ('id_proof_1', models.ImageField(upload_to='document')),
                ('id_proof_2', models.ImageField(upload_to='document')),
                ('id_proof_3', models.ImageField(upload_to='document')),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('payment_type', models.CharField(max_length=50, null=True)),
                ('passport_no', models.CharField(max_length=100, null=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('date_of_expiry', models.DateField(blank=True, null=True)),
                ('date_of_arrival', models.DateField(blank=True, null=True)),
                ('visa_no', models.CharField(max_length=100, null=True)),
                ('date_of_expiry_visa', models.DateField(blank=True, null=True)),
                ('date_of_issue_visa', models.DateField(blank=True, null=True)),
                ('employed_india', models.BooleanField(null=True)),
                ('duration_stay_india', models.CharField(max_length=50, null=True)),
                ('check_in', models.DateField(auto_now_add=True)),
                ('check_out', models.DateField(null=True)),
                ('no_of_adult', models.IntegerField()),
                ('room', models.CharField(max_length=20, null=True)),
                ('no_of_children', models.IntegerField()),
                ('remark', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('plan', models.CharField(max_length=200, null=True)),
                ('booking_agency', models.CharField(max_length=50, null=True)),
                ('selfi', models.ImageField(upload_to='media/selfi')),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Reject'), ('waiting', 'Waiting for Approval')], max_length=20, null=True)),
                ('signature', models.ImageField(upload_to='media/sign')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelusers')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='GoogleQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='qr')),
                ('link', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('place_id', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deactivated', 'Deactivated'), ('waiting', 'Waiting for Approval')], max_length=20, null=True)),
                ('package', models.CharField(choices=[('filter', 'Filter'), ('without_filter', 'Without Filter')], max_length=20, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('amount', models.CharField(max_length=50, null=True)),
                ('agreement', models.FileField(null=True, upload_to='media')),
                ('new', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('rating', models.IntegerField()),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='express_checkin.googleqr')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proofs', models.FileField(upload_to='document')),
                ('checkins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express_checkin.checkin')),
            ],
        ),
    ]
