# Generated by Django 4.0.1 on 2022-06-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='grc_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
