# Generated by Django 4.0.1 on 2022-06-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_checkin', '0002_checkin_grc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='purpose_of_visit',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
