# Generated by Django 4.0.1 on 2022-06-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_checkin', '0003_checkin_purpose_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='id_proof_back',
            field=models.ImageField(null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='otherdocuments',
            name='id_proofs_back',
            field=models.FileField(null=True, upload_to='document'),
        ),
    ]
