# Generated by Django 4.0.6 on 2022-08-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_code', models.CharField(max_length=20, unique=True)),
                ('restaurant_name', models.CharField(max_length=80)),
                ('owner_name', models.CharField(max_length=80)),
                ('type_of', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('coffeeshop', 'CoffeeShop')], default='restaurant', max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=500, null=True)),
                ('user_mobile', models.CharField(max_length=15, null=True)),
                ('profile_photo', models.ImageField(upload_to='media')),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('tablecount', models.CharField(max_length=15, null=True)),
                ('amount', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('duration', models.FloatField(max_length=10)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.FileField(null=True, upload_to='media')),
                ('admin_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_user.adminusers')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OtherDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableqr', models.FileField(upload_to='document')),
                ('restaurantname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantuser')),
            ],
        ),
    ]
