# Generated by Django 4.0.6 on 2022-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurantuser_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantuser',
            name='property_code',
            field=models.CharField(max_length=20),
        ),
    ]
