# Generated by Django 4.0.6 on 2022-08-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurantuser_property_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
