# Generated by Django 4.0.6 on 2022-08-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurantuser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableqrcodes',
            name='tableqr',
            field=models.FileField(null=True, upload_to='document'),
        ),
    ]
