# Generated by Django 4.0.6 on 2022-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_tableqrcodes_tableqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
