# Generated by Django 4.0.6 on 2022-08-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurantuser_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Waiting', 'Waiting for Approval'), ('Deactivate', 'Deactivate')], max_length=60, null=True),
        ),
    ]
