# Generated by Django 4.0.6 on 2022-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurantuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='username',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
