# Generated by Django 4.0.6 on 2022-08-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_developeradmin_is_restaurantmenucard'),
        ('restaurant', '0010_restaurantuser_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantuser',
            name='admin_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_user.adminusers'),
        ),
    ]
