# Generated by Django 4.0.6 on 2022-08-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_waiter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='waiter',
            new_name='Restaurantwaiter',
        ),
    ]
