# Generated by Django 4.0.6 on 2022-08-29 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_restaurantfooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantwaiter',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantuser'),
        ),
    ]
