# Generated by Django 4.0.6 on 2022-08-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_restaurantwaiter_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFoodmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=80, null=True)),
                ('price', models.CharField(max_length=80, null=True)),
                ('fooditem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantfooditem')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantuser')),
            ],
        ),
    ]
