# Generated by Django 4.0.1 on 2022-05-19 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=20)),
                ('with_filter', models.BooleanField(default=False, null=True)),
                ('without_email', models.BooleanField(default=False, null=True)),
                ('without_filter', models.BooleanField(default=False, null=True)),
                ('without_backend', models.BooleanField(default=False, null=True)),
                ('profile_photo', models.ImageField(upload_to='media')),
                ('property_code', models.CharField(max_length=20, unique=True)),
                ('default_caption', models.CharField(max_length=300, null=True)),
                ('amount', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('url_checkin', models.CharField(max_length=200, null=True)),
                ('total', models.FloatField(null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('checkin_qr', models.ImageField(null=True, upload_to='qr')),
                ('property_images', models.ImageField(upload_to=None)),
                ('type_of', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('resort', 'Resort'), ('lodge', 'Lodge'), ('service', 'Service Apartment'), ('home_stay', 'Home stay'), ('house_boat', 'House Boat')], default='hotel', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(max_length=10)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('insta_id', models.CharField(max_length=200)),
                ('page_id', models.CharField(max_length=200, null=True)),
                ('google_link', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200)),
                ('twitter_id', models.CharField(max_length=50, null=True)),
                ('agreement', models.FileField(null=True, upload_to='media')),
                ('trip_adviser_link', models.CharField(max_length=200, null=True)),
                ('facebook_access_token', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Waiting', 'Waiting for Approval'), ('Deactivate', 'Deactivate')], max_length=60, null=True)),
                ('qr_code', models.ImageField(null=True, upload_to='qr')),
                ('google', models.BooleanField(default=False)),
                ('trip_adviser', models.BooleanField(default=False)),
                ('social_media', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('express_checkin', models.BooleanField(default=False)),
                ('g_t', models.BooleanField(default=False)),
                ('inhouse', models.BooleanField(default=False)),
                ('t_g', models.BooleanField(default=False)),
                ('access_token_end_date', models.DateField(null=True)),
                ('email_content', models.CharField(max_length=500, null=True)),
                ('email_image', models.ImageField(null=True, upload_to='email')),
                ('offer_caption', models.CharField(max_length=100, null=True)),
                ('coupon_code', models.CharField(max_length=30, null=True)),
                ('extra', models.CharField(max_length=100, null=True)),
                ('admin_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_user.adminusers')),
                ('hotel_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Renewals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renew_date', models.DateTimeField()),
                ('google', models.BooleanField(default=False)),
                ('trip_adviser', models.BooleanField(default=False)),
                ('in_house', models.BooleanField(default=False)),
                ('social_media', models.BooleanField(default=False)),
                ('express_checkin', models.BooleanField(default=False)),
                ('g_t', models.BooleanField(default=False)),
                ('t_g', models.BooleanField(default=False)),
                ('agreement', models.FileField(null=True, upload_to='media')),
                ('duration', models.IntegerField()),
                ('amount', models.FloatField(default=0, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelusers')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('working', 'Working'), ('solved', 'Solved')], max_length=100)),
                ('admin_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_user.adminusers')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelusers')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
