# Generated by Django 4.0.1 on 2022-06-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelusers',
            name='text_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='hotelusers',
            name='whatsapp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
