# Generated by Django 4.0.1 on 2022-06-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelusers_text_sms_hotelusers_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelusers',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
